# # collect interval
# interval = 15

## if machine has many network connections, use this plugin may exhaust your cpu resource, diable connection stat to avoid this
disable_connection_stats = false

tcp_ext = false
ip_ext = false