[[instances]]
# endpoint region 参考 https://help.aliyun.com/document_detail/28616.html#section-72p-xhs-6qt
# 接入地址
endpoint=""
# 地域ID
region=""
http_proxy=""

# namespace 参考https://help.aliyun.com/document_detail/163515.htm?spm=a2c4g.11186623.0.0.44d65c58mhgNw3
namespace=""
# metric name 参考 https://help.aliyun.com/document_detail/163515.htm?spm=a2c4g.11186623.0.0.401d15c73Z0dZh
# 参考页面中的Metric Id 填入下面的metricName ,页面中包含中文的Metric Name对应接口中的Description
metricName=""


# Action 支持DescribeMetricData DescribeMetricLast DescribeMetricList DescribeMetricTop
# default action is DescribeMetricLast
# DescribeMetricList https://help.aliyun.com/document_detail/51936.html
# DescribeMetricLast https://help.aliyun.com/document_detail/51939.html
# DescribeMetricData https://help.aliyun.com/document_detail/114917.html
# DescribeMetricTop https://help.aliyun.com/document_detail/114918.html
## DescribeMonitorResourceQuotaAttribute https://help.aliyun.com/document_detail/201086.html
action=""
# 必须为60s的倍数
period=""