[[instances]]
region="cn-beijing"
endpoint="metrics.cn-hangzhou.aliyuncs.com"
access_key_id="your-access-key-id"
access_key_secret="your-access-key-secret"
delay="10m"
period="60s"
namespaces=["acs_ecs_dashboard"]
[[instances.metric_filters]]
metric_names=["cpu_cores","vm.TcpCount"]
namespace=""
ratelimit=25
catch_ttl="1h"
timeout="5s"
