[[instances]]
metrics_name_prefix = "kafka_"
  
metrics_drop = [
  "*_EventType",
  "*_MeanRate",
  "*_RateUnit",
  "*_LatencyUnit",
  "*_OneMinuteRate",
  "*_FiveMinuteRate",
  "*_FifteenMinuteRate",
  "*_75thPercentile",
  "*_95thPercentile",
  "*_98thPercentile",
  "*_999thPercentile",
  "*_Min",
  "*_Max",
  "*_Mean",
  "*_StdDev",
  "request_*Ms_Count",
  "request_RequestQueueTimeMs_*",
  "request_LocalTimeMs_*",
  "request_RemoteTimeMs_*",
  "request_ThrottleTimeMs_*",
  "request_ResponseSendTimeMs_*",
  "request_ResponseQueueTimeMs_*",
  "request_RequestBytes_50thPercentile",
  "request_RequestBytes_99thPercentile"
]
  
urls = ["http://localhost:8090/jolokia"]
labels = { cluster = "kafka-cluster-demo" }

# OfflinePartitionsCount
[[instances.metric]]
  name         = "controller"
  mbean        = "kafka.controller:name=*,type=*"
  field_prefix = "$1_"

[[instances.metric]]
  name         = "replica_manager"
  mbean        = "kafka.server:name=*,type=ReplicaManager"
  field_prefix = "$1_"

[[instances.metric]]
  name         = "purgatory"
  mbean        = "kafka.server:delayedOperation=*,name=*,type=DelayedOperationPurgatory"
  field_prefix = "$1_"
  field_name   = "$2"

[[instances.metric]]
  name         = "zookeeper"
  mbean        = "kafka.server:name=*,type=SessionExpireListener"
  field_prefix = "$1_"

[[instances.metric]]
  name     = "user"
  mbean    = "kafka.server:user=*,type=Request"
  field_prefix = ""
  tag_keys = ["user"]

[[instances.metric]]
  name         = "request"
  mbean        = "kafka.network:name=*,request=*,type=RequestMetrics"
  field_prefix = "$1_"
  tag_keys     = ["request"]

[[instances.metric]]
  name         = "topics"
  mbean        = "kafka.server:name=*,type=BrokerTopicMetrics"
  field_prefix = "$1_"

[[instances.metric]]
  name         = "topic"
  mbean        = "kafka.server:name=*,topic=*,type=BrokerTopicMetrics"
  field_prefix = "$1_"
  tag_keys     = ["topic"]

# LogStartOffset LogEndOffset Size NumLogSegments
# [[instances.metric]]
#   name       = "loginfo"
#   mbean      = "kafka.log:name=*,partition=*,topic=*,type=Log"
#   field_name = "$1"
#   tag_keys   = ["topic", "partition"]

# OfflineLogDirectoryCount
[[instances.metric]]
  name       = "logmanager"
  mbean      = "kafka.log:name=*,type=LogManager"
  field_name = "$1"

# LogDirectoryOffline
[[instances.metric]]
  name       = "logmanager"
  mbean      = "kafka.log:name=*,logDirectory=*,type=LogManager"
  field_name = "$1"
  tag_keys   = ["logDirectory"]

[[instances.metric]]
  name       = "cluster"
  mbean      = "kafka.cluster:name=UnderReplicated,partition=*,topic=*,type=Partition"
  field_name = "UnderReplicatedPartitions"
  tag_keys   = ["topic", "partition"]

[[instances.metric]]
  name  = "java_runtime"
  mbean = "java.lang:type=Runtime"
  paths = ["Uptime"]

[[instances.metric]]
  name  = "java_memory"
  mbean = "java.lang:type=Memory"
  paths = ["HeapMemoryUsage", "NonHeapMemoryUsage", "ObjectPendingFinalizationCount"]

[[instances.metric]]
  name     = "java_garbage_collector"
  mbean    = "java.lang:name=*,type=GarbageCollector"
  paths    = ["CollectionTime", "CollectionCount"]
  tag_keys = ["name"]

[[instances.metric]]
  name  = "java_last_garbage_collection"
  mbean = "java.lang:name=G1 Young Generation,type=GarbageCollector"
  paths = ["LastGcInfo/duration"]
  # paths = ["LastGcInfo/duration", "LastGcInfo/GcThreadCount", "LastGcInfo/memoryUsageAfterGc"]

[[instances.metric]]
  name  = "java_threading"
  mbean = "java.lang:type=Threading"
  paths = ["TotalStartedThreadCount", "ThreadCount", "DaemonThreadCount", "PeakThreadCount"]

[[instances.metric]]
  name  = "java_class_loading"
  mbean = "java.lang:type=ClassLoading"
  paths = ["LoadedClassCount", "UnloadedClassCount", "TotalLoadedClassCount"]

[[instances.metric]]
  name     = "java_memory_pool"
  mbean    = "java.lang:name=*,type=MemoryPool"
  paths    = ["Usage", "PeakUsage", "CollectionUsage"]
  tag_keys = ["name"]