global:
  scrape_interval: 15s
  #external_labels:
  #  cluster: test
  #  replica: 0

scrape_configs:
  - job_name: "categraf-scrape-metrics"
    static_configs:
      - targets: ["172.16.3.186:8080"]

  - job_name: "categraf-kubernetes-apiservers"
    metrics_path: "/metrics"
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      insecure_skip_verify: true
    authorization:
      credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels:
          [
            __meta_kubernetes_namespace,
            __meta_kubernetes_service_name,
            __meta_kubernetes_endpoint_port_name,
          ]
        action: keep
        regex: default;kubernetes;https
  - job_name: "categraf-core-dns"
    metrics_path: "/metrics"
    kubernetes_sd_configs:
      - role: endpoints
    scheme: http
    relabel_configs:
      - source_labels:
          [
            __meta_kubernetes_namespace,
            __meta_kubernetes_service_name,
            __meta_kubernetes_endpoint_port_name,
          ]
        action: keep
        regex: kube-system;kube-dns;metrics

remote_write:
  - url: 'http://172.31.62.213/prometheus/v1/write'
